services:
  product-service:
    image: product-service:1.0
    container_name: product-service
    restart: on-failure
    profiles:
      - product
    ports:
      - "7070:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://product-mysql:3306/product_db
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product
    depends_on:
      product-mysql:
        condition: service_healthy
  product-mysql:
    image: mysql:8.4
    container_name: product-mysql
    restart: unless-stopped
    profiles:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: product
      MYSQL_PASSWORD: product
    ports:
      - "3306:3306"
    volumes:
      - product_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "product", "-pproduct"]
      interval: 5s
      timeout: 5s
      retries: 10
  order-mysql:
    profiles:
      - order
    image: mysql:8.4
    container_name: order-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order
      MYSQL_PASSWORD: order

    ports:
      - "3307:3306"

    volumes:
      - order_mysql_data:/var/lib/mysql
volumes:
  product_mysql_data:
    driver: local
  order_mysql_data:
    driver: local