services:
  product-mysql:
    image: mysql:8.4
    container_name: product-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: product
      MYSQL_PASSWORD: product
    ports:
      - "3306:3306"
    volumes:
      - product_mysql_data:/var/lib/mysql
  order-mysql:
    image: mysql:8.4
    container_name: order-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order
      MYSQL_PASSWORD: order

    ports:
      - "3307:3306"

    volumes:
      - order_mysql_data:/var/lib/mysql
volumes:
  product_mysql_data:
    driver: local
  order_mysql_data:
    driver: local