server:
  port: 7070
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: product
    password: product
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true