INSERT IGNORE  INTO product
(name, description, sku, price, stock_quantity, active, created_at, updated_at)
VALUES
    ('iPhone 17',
     'Apple iPhone 17 256GB',
     'PHONE-IPHONE17-256',
     999.99,
     25,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('iPhone 17 Pro',
     'Apple iPhone 17 Pro 512GB',
     'PHONE-IPHONE17-PRO',
     1299.99,
     15,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Samsung Galaxy S25',
     'Samsung Galaxy S25 256GB',
     'PHONE-GALAXY-S25',
     899.99,
     30,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Google Pixel 10',
     'Google Pixel 10 256GB',
     'PHONE-PIXEL10-256',
     799.99,
     20,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('MacBook Pro 14',
     'Apple MacBook Pro 14 inch M4',
     'LAPTOP-MACBOOK-PRO-14',
     1999.99,
     10,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('MacBook Air 15',
     'Apple MacBook Air 15 inch M4',
     'LAPTOP-MACBOOK-AIR-15',
     1499.99,
     18,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Dell XPS 15',
     'Dell XPS 15 Intel Core Ultra laptop',
     'LAPTOP-DELL-XPS15',
     1599.99,
     12,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Lenovo ThinkPad X1 Carbon',
     'Lenovo ThinkPad X1 Carbon business laptop',
     'LAPTOP-THINKPAD-X1',
     1399.99,
     22,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Sony WH-1000XM6',
     'Sony wireless noise cancelling headphones',
     'AUDIO-SONY-WH1000XM6',
     399.99,
     40,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Apple AirPods Pro',
     'Apple AirPods Pro wireless earbuds',
     'AUDIO-AIRPODS-PRO2',
     249.99,
     50,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Samsung Galaxy Buds',
     'Samsung wireless Bluetooth earbuds',
     'AUDIO-GALAXY-BUDS',
     149.99,
     35,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Logitech MX Master 3S',
     'Wireless ergonomic mouse',
     'MOUSE-MX-MASTER-3S',
     99.99,
     75,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Logitech MX Keys',
     'Wireless mechanical-style keyboard',
     'KEYBOARD-MX-KEYS',
     119.99,
     60,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Keychron K8 Pro',
     'Wireless mechanical keyboard',
     'KEYBOARD-KEYCHRON-K8',
     129.99,
     35,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Samsung 32 Inch Monitor',
     '32 inch 4K UHD monitor',
     'MONITOR-SAMSUNG-32',
     449.99,
     20,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('LG UltraWide 34',
     '34 inch UltraWide QHD monitor',
     'MONITOR-LG-ULTRAWIDE34',
     599.99,
     14,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('PlayStation 5',
     'Sony PlayStation 5 gaming console',
     'CONSOLE-PS5',
     499.99,
     12,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Xbox Series X',
     'Microsoft Xbox Series X gaming console',
     'CONSOLE-XBOX-SERIES-X',
     499.99,
     8,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Nintendo Switch 2',
     'Nintendo Switch 2 gaming console',
     'CONSOLE-SWITCH-2',
     449.99,
     16,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('Anker Power Bank',
     'Anker 20000mAh portable power bank',
     'ACCESSORY-ANKER-20K',
     59.99,
     100,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),
    ('Old iPhone Case',
     'Discontinued iPhone protective case',
     'ACCESSORY-OLD-CASE',
     19.99,
     0,
     FALSE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    ('USB-C Cable',
     'USB-C fast charging cable',
     'ACCESSORY-USB-C-CABLE',
     14.99,
     0,
     TRUE,
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP)
    ;