apiVersion: v1
kind: Service
metadata:
  name: product-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: product-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-mysql
spec:
  serviceName: product-mysql
  replicas: 1
  selector:
    matchLabels:
      app: product-mysql
  template:
    metadata:
      labels:
        app: product-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: product-mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: product-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: product-mysql-data
              mountPath: /var/lib/product-mysql
  volumeClaimTemplates:
    - metadata:
        name: product-mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi